name: CI for .NET MAUI Demo project

on: [push, pull_request]

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  SOLUTION_NAME: IntroductionToDotNetMAUI/Demo
  PROJECT_NAME: DotNetMauiDemo

jobs:
  build:
    name: Build .NET MAUI Demo project
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
    
    - name: Install .NET workloads
      shell: pwsh
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install maccatalyst
        dotnet workload install maui
      
    - name: Build ${{env.SOLUTION_NAME}}/${{env.PROJECT_NAME}}.csproj
      run: dotnet build "${{env.SOLUTION_NAME}}/${{env.PROJECT_NAME}}/${{env.PROJECT_NAME}}.csproj"
