name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SCHEME: "DogBreedsApp"
  SOLUTION: "Build-iOS-with-SwiftUI/Demo/"
  PROJECT: "DogBreedsApp.xcodeproj"
  DESTINATION: "platform=iOS Simulator,OS=16.2,name=iPhone 14"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        
      - name: install simulator
        run: xcversion simulators --install='iOS 16.2'

      - name: Prepare iOS 16.2 simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_14.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 16.2.simruntime
          xcrun simctl list runtimes
          xcrun simctl create custom-test-device "iPhone 14" "com.apple.CoreSimulator.SimRuntime.iOS-16-2"
          xcrun simctl list devices 14.0

#         with:
#           xcode-version: "latest-stable"  # Replace with your desired Xcode version

#       - name: find simulator version
#         run: |
#           xcrun simctl list devices
#       - name: Install dependencies
#         run: |
#           cd "${{ env.SOLUTION }}"
#           swift package resolve
#           swift package update
#       - name: boot simulator
#         run: |
#           xcrun simctl boot "iPhone 14"
      - name: build
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: "${{ env.SOLUTION }}${{ env.PROJECT }}"
          scheme: ${{ env.SCHEME }}
          configuration: Release
          destination: "${{ env.DESTINATION }}"
          action: build-for-testing


#       - name: Build and test
#         run: |
#           xcodebuild clean build -project "${{ env.SOLUTION }}${{ env.PROJECT }}" -scheme $SCHEME -destination "${{ env.DESTINATION }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
