name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SOLUTION: "Build-iOS-with-SwiftUI/Demo/"
  PROJECT: "DogBreedsApp.xcodeproj"
  DESTINATION: "platform=iOS Simulator,OS=16.2,name=iPhone 14"

jobs:
  build:
    name: Build iOS example project
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild clean build -project "${{env.SOLUTION}}${{env.PROJECT}}" -sdk iphonesimulator -destination "${{env.DESTINATION}}"
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: iOS IPA
#           path: "output.ipa"
