name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SCHEME: "DogBreedsApp"
  SOLUTION: "Build-iOS-with-SwiftUI/Demo/"
  PROJECT: "DogBreedsApp.xcodeproj"
  DESTINATION: "platform=iOS Simulator"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1

        with:
          xcode-version: "latest-stable"  # Replace with your desired Xcode version

#       - name: find simulator version
#         run: |
#           xcrun simctl list devices
      - name: build
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: "${{ env.SOLUTION }}${{ env.PROJECT }}"
          scheme: ${{ env.SCHEME }}
          configuration: Release
          destination: "${{ env.DESTINATION }}"
          action: build
#       - name: Install dependencies
#         run: |
#           cd "${{ env.SOLUTION }}"
#           swift package resolve
#           swift package update

#       - name: Build and test
#         run: |
#           xcodebuild clean build -project "${{ env.SOLUTION }}${{ env.PROJECT }}" -scheme $SCHEME -destination "${{ env.DESTINATION }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
