name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SCHEME: "DogBreedsApp"
  PROJECT: "Build-iOS-with-SwiftUI/Demo/DogBreedsApp.xcodeproj"
  DESTINATION: "platform=iOS Simulator,OS=14.0,name=iPhone 14 Pro Max"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v1
        with:
          xcode-version: "14.x"  # Replace with your desired Xcode version

      - name: Install dependencies
        run: |
          swift package resolve
          swift package update

      - name: Build and test
        run: |
          xcodebuild clean build test -project $PROJECT -scheme $SCHEME -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
